# Generated by Django 5.2.1 on 2025-05-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_request', '0002_stockrequest_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequestitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
