services:
  db:
    image: postgres:14
    container_name: warelio_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warelio
    ports:
      - "5434:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data
    networks:
      - warelionet


  broker:
    image: rabbitmq:3.12-management
    container_name: warelio_pubsub
    environment:
      RABBITMQ_DEFAULT_USER: warelio
      RABBITMQ_DEFAULT_PASS: warelio
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI port
    healthcheck:
      test:  ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s # every 5 secodns run the commmand
      timeout: 5s
      retries: 5 # hwow many consecutive failures before marking the container as unhealthy
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - warelionet

  dj_warelio:
    build: .
    container_name: dj_warelio
    ports:
       - "8001:8001"
    depends_on:
      - db
      - broker
    volumes:
      - ./static:/Warelio/static
    networks:
      - warelionet

  nginx_default_warelio:
    build: ./nginx
    container_name: nginx_dj_warelio
    ports:
      - "80:80"
    depends_on:
      - dj_warelio
    networks:
      - warelionet
    volumes:
      - ./static:/Warelio/static

volumes:
  psql_data:
  rabbitmq_data:

networks:
  warelionet: